on:
  workflow_dispatch:
  push:

name: Gitee mirror

jobs:
  run:
    name: Gitee mirror
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      # https://github.com/Yikun/hub-mirror-action
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/LmeSzinc
        dst: gitee/lmeszinc
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: 'AzurLaneUncensored'
        force_update: true
        timeout: '30m'
